### ISSUE TITLE
Information boxes

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#11]
Image not displaying properly if included

**Comment by daverees4** [comment]
Can you send an example link?

**Comment by AdamFergusonRCM** [comment]
Sure. There's one on this page. http://www.rcm.ac.uk/newsitebuildarea/international/studyinlondon/

You'll notice an obvious error on this page  with the summary feature link towards the top. Given our revised approach to breakouts I assume this content type needs to be revised. If the problem persists I'll log a separate issue.

**Comment by AdamFergusonRCM** [comment]
This might be because you're tinkering around, but the button class has stopped working for links inside information boxes - the whole thing disappears.

Context:

- Information box content unit
- Section link
- Link class set to "button" in HTML editor

**Comment by daverees4** [comment]
Yes - tinkering - sorry.  Will be back shortly.

**Comment by daverees4** [comment]
That's better - the padding around the image isn't correct - but will get to this when we do the spacing for the elements.

**Comment by AdamFergusonRCM** [comment]
Interestingly, I still can't make the link work - button or otherwise - on one of the boxes. It just won't appear. I've tried deleting the link and adding it again, but to no avail. 

It's the top info box on this page http://www.rcm.ac.uk/newsitebuildarea/international/apply/

**Comment by AdamFergusonRCM** [comment]
It doesn't appear to be a one off or linked specifically to the info box. The alert box on this page has the same issue: http://www.rcm.ac.uk/newsitebuildarea/international/eu/

**Comment by daverees4** [comment]
Now displaying links in Alerts/Info boxes. 

Section links need to be switched on inside the HTML element if they are to appear. Please let me know if you find any others where this is needed.

**Comment by AdamFergusonRCM** [comment]
Okey doke. I think it's safe to say that anywhere we have a link it might potentially be a T4 section or content link. I'm trying to use these much more to aid navigation around the site.
