### ISSUE TITLE
Galleries

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#13]
I noticed something earlier. On pages with multiple galleries only the first will swipe between images. I've since deleted the extra ones (I didn't need them anyway) but some pages are likely to use multiple galleries.

I can send am example next time I get to one.

**Comment by daverees4** [comment]
Please do - hadn't clocked there would be multiple galleries on pages. 

Will need to modify the template a bit.

**Comment by daverees4** [comment]
Just FYI - I've broken all of the gallery buttons - this is in preparation for allowing all galleries.

**Comment by daverees4** [comment]
Galleries now working
