### ISSUE TITLE
Fonts on IE 

### ISSUE THREAD

**Issue by katherineAsmith** [daverees4/rcm-website-version-7#15]
Hi,

Attaching a screen shot from my laptop using IE showing how it's appearing now the vertical breakpoint has been removed. 

I've noticed the fonts seem to have disappeared (they were working previously)
![image](https://cloud.githubusercontent.com/assets/13769414/22366621/8f065e9c-e475-11e6-8a93-b0ae6c823213.png)

Katherine

**Comment by daverees4** [comment]
Okay - great - that's an improvement!

Are fonts working for you here?

http://daverees4.webfactional.com/play/rcm-website-version-7/detail.php

**Comment by katherineAsmith** [comment]
Yes, looks like it:


[cid:381f1132-dd7a-41b5-8991-0b308e4d4a0f]


________________________________

**Comment by daverees4** [comment]
Okay - must be something wrong with the permissions on the fonts.com account

**Comment by daverees4** [comment]
Are the fonts working now?

**Comment by katherineAsmith** [comment]
Yes, seem to. Thanks!


[cid:ce5b747c-46fb-4a24-8399-cb1fa3ba6278]


________________________________
