### ISSUE TITLE
On big screens the hero isn't reaching all the way across. 

### ISSUE THREAD

**Issue by daverees4** [daverees4/rcm-website-version-7#18]

**Comment by katherineAsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/13769414/22473425/cb274d9c-e7d0-11e6-90f9-7dd042e13781.png)

**Comment by katherineAsmith** [comment]
Hi,

I just tried replacing this image with one that is 960x540 (16:9), which are the pixel dimensions we were proposing to use.  Is this size large enough? I would ideally like to start resizing images this week so it would be useful to know if we need to rethink the pixel measurements.

I also noticed, when I tried to change the text underneath the image an error message came up saying the text was longer than 200 characters (it wasn't) so i couldn't update this. 

![image](https://cloud.githubusercontent.com/assets/13769414/22502529/233a3b5e-e865-11e6-95fa-87653d8ccae8.png)

![image](https://cloud.githubusercontent.com/assets/13769414/22502581/5f71a6fc-e865-11e6-88e8-7a25131aa631.png)

**Comment by daverees4** [comment]
Image needs to be bigger - dimensions TBC

Not sure why content wasn't working - have increased the max size to 1000 chars

**Comment by katherineAsmith** [comment]
Hi David, 

I just tried to replace the text under the hero image and I got the same error message again. Can you check the word limit? Have you put 20 rather than 200?

Thanks,
katherine

**Comment by daverees4** [comment]
Not sure why that still wasn't working - so I recreated that element.  It
seems to be fine now:

http://www.rcm.ac.uk/2017testarea/homepagetest/

**Comment by katherineAsmith** [comment]
Thanks David. Just tested it again and noticed that if you add a link in the text, the link doesn't show.

**Comment by daverees4** [comment]
Just turned on section links for that element - now showing

**Comment by katherineAsmith** [comment]
Great, thanks!
