### ISSUE TITLE
Remove feature box summary breakout divs

### ISSUE THREAD

**Issue by daverees4** [daverees4/rcm-website-version-7#22]

**Comment by AdamFergusonRCM** [comment]
Hi David

You wanted examples of this.

There's one here: http://www.rcm.ac.uk/newsitebuildarea/international/studyinlondon/

**Comment by AdamFergusonRCM** [comment]
There are also two side-by-side here: http://rcm-webcms.rcm.ac.uk/terminalfour/SiteManager?ctfn=publish&fnno=30&sid=4452&chid=6&lang=en&ms=false&ss=false&ede=false&sp=false&spc=false&act=32

You can see they don't quite line up in the same way as rollover boxes

Thanks

A

**Comment by daverees4** [comment]
We're going to make two elements:

Inline Summary - which works like an inline element

Feature link summary - which is like the rollover content

**Comment by daverees4** [comment]
Needs to pull in news items

**Comment by daverees4** [comment]
There's another issue about pulling in news items to summaries so will close this
