### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#23]
This is a small one.

I think quotes should sit entirely within the text column at S3, unless forced into a full breakout. The centre alignment looks odd when the quote stretches into the left margin.

This page is a good example: http://www.rcm.ac.uk/newsitebuildarea/life/preparingforprofession/facilities/

**Comment by AdamFergusonRCM** [comment]
Also, quote galleries with only a single quote still have the fade transition, which means the quote disappears and reappears periodically.

**Comment by katherineAsmith** [comment]
I've also noticed that it doesn't seem to pull through more than 2 quotes. 

This page is a good example, where there are about 6 quotes in the template but only two are coming through http://www.rcm.ac.uk/newsitebuildarea/junior/

**Comment by daverees4** [comment]
I think issues are fixed now - I couldn't find an example to check. 

You might need to refresh this js file to see fade removed from single item carousels - http://daverees4.webfactional.com/play/rcm-website-version-7/js/app.js

Please reopen if still not right.

**Comment by AdamFergusonRCM** [comment]
Thanks David

Those two issues have indeed been fixed (as perfectly exemplified here: http://www.rcm.ac.uk/newsitebuildarea/life/studentsupport/).

Unfortunately the quotes are now too far to the right if used in breaktouts. See this example: http://www.rcm.ac.uk/newsitebuildarea/international/supportandscholarships/

**Comment by daverees4** [comment]
Damn . . .

**Comment by daverees4** [comment]
I've had to add an extra element to the template "inline?" that needs to be checked when creating quotes inline - this will add the extra margin required on s3.

**Comment by AdamFergusonRCM** [comment]
David, can we add another 30 characters to the limit for quote authors please?

Thanks

**Comment by AdamFergusonRCM** [comment]
Hi, can we up the number of characters for the actual quotes too? Let's make it 200 rather than 300

Thanks
