### ISSUE TITLE
HP Pavillion issues: menus

### ISSUE THREAD

**Issue by katherineAsmith** [daverees4/rcm-website-version-7#25]
Hello,

Attaching two screen shots of how it's displaying on my home laptop

1. Shows the bottom half of the menu falling off the screen at S3 (it's fine at S2)

2. At S2, you loose a tiny bit of the main content area on the left.

![image](https://cloud.githubusercontent.com/assets/13769414/22567574/5df4d7a8-e988-11e6-8152-a3005b144ad4.png)
![image](https://cloud.githubusercontent.com/assets/13769414/22567590/6df51244-e988-11e6-9260-b356f5271bc4.png

**Comment by daverees4** [comment]
Hi Katherine, 

I've fixed issue 2 - there you shouldn't get that problem of the content overlapping on the left hand side in s2. 

Issue 1 - isn't really an issue, the menu is working correctly at s3 your screen is just too small to display it.   Do you know the viewport size? You can find it out by going here: http://viewportsizes.com/mine/

Some possible workarounds:
- increase the width when screen goes from s2 to s3 to exclude this device from s3
- redesign the menu again to have less height, even at s3.
