### ISSUE TITLE
Concertinas

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#28]
Hi David

Just for clarification (my brain has gone all smushy)

For the drawn-in concertinas, does ALL the content have to be in the subfolder or can normal text go straight into the concertina content unit if that text is supposed to appear first (ie above content in the subfolder)?

I'm having difficulty bringing through info boxes, but I think I'm missing something obvious

Thanks

**Comment by daverees4** [comment]
Yes - that's right.

But for any type of template to appear in concertinas it needs a special
template to be created.  I don't think we've done one for info boxes yet.

I can make one now.

**Comment by daverees4** [comment]
Okay - added info boxes to the content templates that can be added to concertinas

So you should see them being brought in if you add them to the subfolder

**Comment by daverees4** [comment]
Those five content templates can now be added to concertinas!

**Comment by AdamFergusonRCM** [comment]
Super, thanks!

I'm in two minds about adding contact cards as well. However, it creates a real stylistic inconsistency that really bugs me, so I might find another solution to displaying this information.

**Comment by AdamFergusonRCM** [comment]
Oh, I think we still need more options for concertina subfolders. I think we said up to 11. Perhaps 12 would be a more rational number!

Thanks

Adam

**Comment by daverees4** [comment]
Okay!  no problem!

**Comment by daverees4** [comment]
There's now 12 concertina subfolders that can be selected when creating a concertina

**Comment by AdamFergusonRCM** [comment]
Can we add standalone headings to the content types allowed in concertinas please? Thanks!

**Comment by AdamFergusonRCM** [comment]
Concertina 11 on [this page](http://www.rcm.ac.uk/newsitebuildarea/apply/auditions/auditionlocation/) is picking up the content in the concertina-10 folder.

**Comment by daverees4** [comment]
Had the ids wrong and was picking up wrong sub folder - should be fine now.

**Comment by AdamFergusonRCM** [comment]
Hi David

Can we allow PDFs in concertinas too please? Thanks!

**Comment by daverees4** [comment]
done

**Comment by AdamFergusonRCM** [comment]
Hi David

Sorry to open this again, but I don't think Standalone headings are coming through

Cheers

A

**Comment by daverees4** [comment]
No worries!  Should be available now!

**Comment by AdamFergusonRCM** [comment]
Sorry to reopen this one again!

Turns out the we need contact cards in concertinas too.

Thanks

A

**Comment by daverees4** [comment]
Should be available now
