### ISSUE TITLE
Social Media Icons on Safari

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#3]
I noticed last night that the social media icons were stretching too far to the right of the screen on Safari (desktop). Not sure whether this is the icons themselves, the container they're in or the footer as a whole that's too far to the right.

**Comment by AdamFergusonRCM** [comment]
It has just dawned on me. Could this be related to Katherine's 'bouncing' issue? Is there extra width somewhere, extending beyond the edge of the screen leading some browsers to think that horizontal scrolling should be an option?

I noticed that the browser (god knows what it is) on the smart TV we used yesterday allowed some horizontal scrolling, which pushed the content underneath the menu bar.

Just a thought

**Comment by daverees4** [comment]
This is right - we will need another icon set without so much padding and then the left-right scroll will stop.

**Comment by AdamFergusonRCM** [comment]
While we're talking about icons, we need to take account of the fact that we now have a WeChat account. This will have to be raised with Cog, preferably before they issue a new set of icons.

**Comment by daverees4** [comment]
Have removed social icons from the design to be returned when we have new icon set and design to feature the wechat icon.
