### ISSUE TITLE
In page links

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#34]
I've added some InPageLinks to a subfolder called Anchor Links on this page: http://www.rcm.ac.uk/newsitebuildarea/apply/auditions/auditionlocation/

However, as you can see, they're not showing. Is this a bug or am I doing something daft?

A

**Comment by AdamFergusonRCM** [comment]
As an additional point, content links (as opposed to section links) don't seem to work if we've set a custom anchor. My guess is that the custom anchor ID overrides the T4 ID but that the system for linking to specific bits of content looks for the T4 default. That seems to be what's happening in the generated target URL when I go and have a look at it.

**Comment by daverees4** [comment]
Section links have been added to every page. 

Content links will only work if the content ids are added to the template.  We will need to discuss where you would like to use content links and add this extra information.
