### ISSUE TITLE
Alert boxes

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#35]
I've noticed a styling error at S3 with Alert Boxes (but not Info Boxes). The text is not indented from the left.

![image](https://cloud.githubusercontent.com/assets/25058967/22884275/ff31007c-f1eb-11e6-8c4a-f055b1f910ac.png)

Thanks

**Comment by AdamFergusonRCM** [comment]
Actually, the problem does exist with Info Boxes, just not as severely.

![image](https://cloud.githubusercontent.com/assets/25058967/23951983/d5f58c56-0987-11e7-83a8-9e14558f1efd.png)

**Comment by AdamFergusonRCM** [comment]
Both types of box extend too far to the right

**Comment by AdamFergusonRCM** [comment]
Regarding the spacing within the boxes at S3:

- The text does not have to align withe the left edge of the main content column.
- The left and right padding should be even

I think this has actually been fixed now, but I thought I'd have the spec here for our records.

The boxes extending too far to the right is still and outstanding issue, though

**Comment by daverees4** [comment]
I think this should be better now - can you check on your larger screen?

**Comment by AdamFergusonRCM** [comment]
Much better. The green box on /international is still extending a smidge too far to the right. It wouldn't be noticeable if it weren't for all the boxes and hard edges, annoyingly.

**Comment by daverees4** [comment]
I've nudged it a tiny bit right - looks right now.
