### ISSUE TITLE
Staff Profiles: personal email in contact information

### ISSUE THREAD

**Issue by katherineAsmith** [daverees4/rcm-website-version-7#43]
I've noticed that when only the personal email is ticked on an individual's profile, this is not showing up on their profile.

here's an example: http://www.rcm.ac.uk/newsitebuildarea/brass/professors/details/?id=01881 

Nigel's personal email is in the XML - it's just not being brought through.

Can you check this?

Thanks,
Katherine

**Comment by daverees4** [comment]
Should be working properly now.
