### ISSUE TITLE
Landing pages

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#51]
The landing pages are all now in T4 so I'm opening this thread to collate bugs and comments.

Technical errors to note:
- Feature video formatting is a bit wild!
- [International](http://www.rcm.ac.uk/newsitebuildarea/international/) and [Life](http://www.rcm.ac.uk/newsitebuildarea/life/) pages extend too far to the left, including the footer. I think it might be the feature video that's doing this.
- I'm not convinced that two feature boxes sitting side-by-side are always the same size.

Other points:
-  These landing pages are good places to test spacing!
- Landing pages do not show name at top of menu at S2 and S3 as per designs and as happens on faculty pages.

I'm sure other things will crop up.

I have experimented with sizes for hero heading text, but I've left my jottings on my desk and I'm now working from home. I'll send tomorrow.

Thanks

**Comment by daverees4** [comment]
I think everything here is fixed or covered in other open issues - please reopen if not
