### ISSUE TITLE
Special characters reverting to fallback fonts

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#62]
This happens in the recent visiting artists concertina on the brass landing page. Only seems to happen with some characters. Are these not in the Futura character set?

**Comment by daverees4** [comment]
Yes - seems some exteneded - eastern european? chars not available in our font set?

We have purchased Latin 1 - it looks like this ć is in the latin-extended. 

Recommend replacing with normal c

**Comment by AdamFergusonRCM** [comment]
Hi David

**Comment by daverees4** [comment]
As far as I can see it doesn't have it - same thing happens when using the demo on fonts.com

![download 1](https://cloud.githubusercontent.com/assets/1063119/24355304/4ac1572c-12ed-11e7-9c9f-769965301522.png)

**Comment by daverees4** [comment]
(the webfont has a smaller character set to the downloadable desktop version)

**Comment by AdamFergusonRCM** [comment]
I will inform Katherine. We need to find a solution to this eventually so we don't end up misspelling people's names.
