### ISSUE TITLE
Revised spacing for some elements

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#64]
Hi David

As promised, here are some revised specs for  headings and lists, plus a couple of other things I noticed while testing sizes.

I imagine most of these will be as simple as adding margins, but do feel free to insert the space some other way if you think that will work better.

**.h2**
At S1: 1.75rem above, 0.25rem below
At S2: 2.5rem above
At S3: 2.75rem above

**.h3**
At S1: 0.25rem above
At S2: 1.75rem above
At S3: 2rem above
_Note: can we give video titles a custom class so they aren't effected?_

**.ul**
At all sizes: 1.5rem above and below

**.li**
At all sizes: 0.85rem below

**.button**
At all sizes: 0.5rem above and below
_Note: can we exclude anchor link buttons from this rule?_

**Info boxes**
At S1: 1.25rem margin at bottom
Below 549px width: 0.5rem margin below

**Comment by AdamFergusonRCM** [comment]
Exceptions I've noted so far:

- Job titles on staff profiles
- Postnominals on staff profiles

Both use h3 at the moment. They can keep h3 font styling, but both actually look fine with no top or bottom margin at all. The surrounding elements provide enough space without needing to add or subtract anything.

**Comment by daverees4** [comment]
Think these should be there now 

There might be some more exceptions - had to redo the menu li elements

**Comment by AdamFergusonRCM** [comment]
Thanks David. And well done on spotting the issue with menus!

I have some more of these changes. I'm also reiterating here a few things about spacing in tertiary menus  that aren't quite right yet, just so we've got all the spacing info in one place. Here goes (deep breath)...

**Landing Page template and Faculty Landing Page template**

- Add a 1.4rem gap at the top of the main content column at S2 and S3 only. Should not affect tertiary menu. Idea is to push any content down so it sits flush with the thick line in the menu. Not needed at S1.
- Change not needed on homepage.
- We will instigate a new rule for content appearing at the top: standfirsts will use H6 instead of H5 (details on styling for H6 given below) and quotes will have an option to offset their large margin (already implemented, but I've detailed a tweak below).

**Landing Page Hero Image**

- Change bottom margin to 2.5rem. This should even out spacing between the image and the tertiary menu. In combination with the gap mentioned above, it will also improve visual spacing between the hero and main content.
- Change not needed on homepage hero images.
- InnerPageHeader images will be dealt with separately.

**Detail Pages**

- No changes to page template.
- We will continue to use H5 for standfirsts here.
- We will use InnerPageHeader images as section break images when needed. New formatting tweaks will allow for this.

**Inner Page Header Image**

- Change bottom margin to 0.6rem. This should even out space when quotes are used at the top without undermining any other use of these images.

**H5**

- Change bottom margin to 2rem. This number seems big, but it's the figure that looks best when I try it in Chrome. We may revisit this if it's off.

**H6**

- Uses the same properties and styling as H5 (including the bottom margin change stated above), but has no top margin at all.

**Quotes**

- Can the quotes be centred vertically in their container? The spacing above and below looks either even or uneven depending on how many lines the quote takes up. Small point!
- The system of altering the margin works well, but I've concluded we need two such variants to account for different uses. I've tried to find a compromise solution, but something always ends up looking very wrong. Can we change the name of the tick-box in the content unit to 'Top of Landing Page' and add a second box that says 'Between Feature Boxes'? The specs for the tweaks triggered are as follows:
- Top of Landing Page: changes top margin of quote container to -2.31rem and bottom margin to -1rem.
- Between Feature Boxes: changes top margin of quote container to -2.31rem and leaves the bottom margin as it is.

**Tertiary Menus**

- Change the bottom margin of the unordered list (just here) to 2.75rem.
- Change the line height of text in anchor buttons to 1.5rem.
- Styling on menu list items is not consistent. When an item is highlighted it appears to shift position slightly.

**Unordered list (excluding menus)**

- You just changed these and they look great! But I forgot to ask you to delete the offset in the top margin. It can be set to 0 or deleted entirely. I don't think anything else acts on them.

**Info boxes**
Aside from the issues raised elsewhere in GitHub, there are some inconsistencies with the top padding, bottom padding and space below info boxes at different screen sizes. I mention it here because it's a spacing matter. I'll investigate further and either add revised specs here or on the other issue - whichever seems most appropriate at the time!

Sorry for the long message

**Comment by daverees4** [comment]
I think I've made these changes

**Comment by AdamFergusonRCM** [comment]
I thought I'd posted this in here yesterday, but apparently not! It's still sitting in the comment box unpublished.

Quotes sitting in text content don't seem to be horizontally aligned properly any more. The example below is not set to 'inline', so at S3 it should extend all the way to the left. As you can see it doesn't. Whether 'inline' or not, the quote also extends much further to the right.

![image](https://cloud.githubusercontent.com/assets/25058967/24506984/2baaff98-1557-11e7-8f6f-d01a8b582779.png)


The same problem doesn't exist in breakout sections. However, here we're still seeing clipping on very wide quotes. As seen here (international landing page):

![image](https://cloud.githubusercontent.com/assets/25058967/24506917/f39af3ec-1556-11e7-85ee-08b9f86bbf7b.png)

**Comment by AdamFergusonRCM** [comment]
Also, I think the line height of the text in green anchor buttons is still bigger than 1.5rem

Thanks :)

**Comment by daverees4** [comment]
Can I check first I've got rid of the clipping? - there was some foundation css that was only for very large screens that I think was causing this.

**Comment by AdamFergusonRCM** [comment]
Seems to be working much better now. Do I recall a thing from the spreadsheet saying that the width of quotes should be indented at both sides in breakout areas?

**Comment by AdamFergusonRCM** [comment]
Right, hopefully this will be the final bout of spacing changes. I'm hoping it clears up the last remaining issues and rectifies things that have gone a wee bit squiffy during the last round of updates.

**H2**
- Add a bottom margin of 1rem
- Currently used for feature video title (with its own subclass). Can the parent class be Index Title instead please

**Inline images**
- Add bottom margin of 1.25rem at S1 only

**Contact cards**
- The space between cards is a bit extreme on desktop. Make the bottom margin 2.5rem at S2 and S3.

**Info Boxes**
You did something this morning that fixed one of the major spacing issues, however padding still isn't consistent at all sizes and with all possible combinations of image, heading and text within the boxes. These tweaks should sort it:
- Use custom subclass for h3 headings within info boxes. Keep all parameters as usual h3, but remove top margin
- Use custom subclass for image within info boxes (I think this already happens) and set bottom margin to 2rem at S3 and 1.5rem at S1&2.
- Change top padding inside the boxes to 2.5rem at S3 and 2.25rem at S1 (S2 can stay as it is).

**H6**
- Spacing is great, thanks! However, the text styling is wrong. Font should appear the same as H5.

**InPageLink buttons**
- I know I mentioned this above, but I'll include it here for easier reference: can the line height of the text in InPageLink buttons be set to 1.5rem please?

Many thanks! You're blazing through this stuff and the whole site is really coming together now :)

**Comment by daverees4** [comment]
Do you mean 1rem margin-bottom at s2 and s3?

**Comment by AdamFergusonRCM** [comment]
For which thing?

**Comment by daverees4** [comment]
Sorry h2 - you're said 0.25 rem as S1 above

**Comment by daverees4** [comment]
Also do you want the margin between the inline image and caption or the template and the next thing?

**Comment by AdamFergusonRCM** [comment]
Yeah, that caused some unforeseen issues, do we're going with a different spacing option! I think (and hope) using 1rem bottom margin across all sizes should look okay without causing issues.

**Comment by AdamFergusonRCM** [comment]
From the bottom of the template to the next thing please!

**Comment by daverees4** [comment]
Ah okay - no problem so h2 1rem at all sizes it is.

**Comment by AdamFergusonRCM** [comment]
Just noticed an H2 bug (dammit!). The top margin is pushing down the headings in 'Latest from the faculty' and 'More from the RCM'. These probably need to be made exceptions.

**Comment by AdamFergusonRCM** [comment]
Hi David

Many thanks indeed for all those tweaks. Things are looking fantastic!

The adjustments to Info Box padding I requested have definitely worked well. However, I foolishly forgot to account for the effect on images inside (when used), which have now been pushed down.

To get round this, could the images within info boxes have the following properties added:

- margin-top: 1.1rem at S3
- margin-top: 1.25rem at S1

Should fix it.

I'm still looking into the relationship between line height and text size on the homepage hero. I'll get back to you.

Thanks!

A

**Comment by daverees4** [comment]
Should be done now!
