### ISSUE TITLE
What's on this week on homepage

### ISSUE THREAD

**Issue by katherineAsmith** [daverees4/rcm-website-version-7#65]
Can we change it to 'What's on' for now.  It won't always be 'this week'

Long term, it would be nice if we could change this in T4

**Comment by katherineAsmith** [comment]
Please could you also bring through the venue beneath the time. As you do for the events appearing in the Faculty carousel

**Comment by katherineAsmith** [comment]
And, could you check the size of the venue and spacing above it - on More From Faculty pages, the space is too big and the text also looks too small
http://www.rcm.ac.uk/newsitebuildarea/brass/

**Comment by daverees4** [comment]
Make events selected by "Home"
