### ISSUE TITLE
T4 Content links

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#67]
We talked previously about conflicts between T4 content links and our own custom IDs for bits of content when the two systems were vying for supremacy on the same page. We decided to replace all content links with relative URLs.

Two things have become apparent since then.:

- There are instances where we use content links to move between specific points on different pages. These could have a custom URL too, but would need manually updating in the event of content being moved
- More seriously, T4 content links don't seem to be working at all. For instance, the finance and accommodation links at the top of [this page](http://www.rcm.ac.uk/newsitebuildarea/life/studentsupport/) should go to specific points on our Student Services page. However, both go to the top. What's more, there are no custom IDs on the destination page that might cause a conflict. This leads me to believe the T4 content link functionality is broken in some way.

We need to figure out what's going on here by the end of the week if possible so I can revisit all of our links and check that they work. I had originally set aside some time for adding relative URLs, so I've got the capacity to make changes if necessary.

Thanks

**Comment by AdamFergusonRCM** [comment]
BRAINWAVE!

We seem to be trying to force T4 into our way of thinking. Can we not work the other way round?

Can the anchor link content types we've created be modified to take use a T4 section link rather than a text ID?

**Comment by daverees4** [comment]
I think I've added content ids to all templates that you should need. 

Please let me know if you need any others!

**Comment by AdamFergusonRCM** [comment]
**Hi David

I don't have the option of inserting a T4 content link in the InPageLink content type. It still just has a free text field.

Thanks

A**

**Comment by AdamFergusonRCM** [comment]
In fact, content links seem not to be working at all, even if I replace existing ones. For example, any of the instrument concertinas on any of the faculty pages all have a button linking to a section further down the page, and I can't get them to work.

**Comment by daverees4** [comment]
Are you making links like this?

http://www.rcm.ac.uk/newsitebuildarea/brass/#22606

**Comment by AdamFergusonRCM** [comment]
I'm trying to make them using T4's inbuilt system, so it auto-generates everything after the final /

For example: http://www.rcm.ac.uk/newsitebuildarea/brass/auditionrequirements/#d.en.22638

**Comment by daverees4** [comment]
Ah - I see - didn't realise it needed d.en adding too

The links here see to be working now - http://www.rcm.ac.uk/newsitebuildarea/life/studentsupport/

**Comment by AdamFergusonRCM** [comment]
Ah, that solves it. Hurrah! Would you be able to put the content selection thing in the InPageLink content unit?

Ta very muchly

A

**Comment by daverees4** [comment]
Okay think that should be working!

**Comment by AdamFergusonRCM** [comment]
David, this was and is working fine on everything apart from links aiming for the 'Latest from the faculty' content. They've been added in the same way and the URL seems to change as it should, but the page doesn't focus on the carousel.

**Comment by daverees4** [comment]
Sorry - had forgotten to add the d.en. prefix!
