### ISSUE TITLE
make homepage hero title a link - url - do this first

### ISSUE THREAD

**Issue by daverees4** [daverees4/rcm-website-version-7#85]

**Comment by katherineAsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/13769414/24746976/c3a571c4-1ab2-11e7-8da7-14206327327d.png)
You can see the example on page 64 of the designs (LH image)

**Comment by katherineAsmith** [comment]
And here's a link to the homepage title we will be launching with: http://www.rcm.ac.uk/newsitebuildarea/homepage5/

**Comment by AdamFergusonRCM** [comment]
Hi David
For some reason the link isn't working on mobile

A

**Comment by daverees4** [comment]
Should be working now
