### ISSUE TITLE
New spacing option for H3

### ISSUE THREAD

**Issue by AdamFergusonRCM** [daverees4/rcm-website-version-7#87]
There's a point in Basecamp about space under H3 headings in the 'courses available' sections on faculty pages. I thought I could fix with a quick hack, but' it just makes matters worse. I hadn't realised the issue was at S1 only.

To fix it properly I need to be able to change the bottom margin of _selected_ H3 headings to 0.4rem at S1 only. Is this easiest to do with a custom subclass? David I'll let you advise on the best approach.

Katherine can decide whether or not she wants to make this a priority.

**Comment by daverees4** [comment]
Subclass would be fine to make these changes - please reopen if you'd like to action

**Comment by AdamFergusonRCM** [comment]
Oops! Didn't mean to do that! We can live with this not being done before launch. If we make good progress and have a few minutes in hand we can tuck it in somewhere, but otherwise we'll do it after the site has gone live.
